config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :main_goals do
    resources :sub_goals
  end
  root to: "main_goals#index"
  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/main_goal.rb
class MainGoal < ApplicationRecord
  belongs_to :user
  has_many :sub_goals, dependent: :destroy

  with_options presence: true do
    validates :main_goal
    validates :dead_line
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  belongs_to :user
end

app/models/sub_goal.rb
class SubGoal < ApplicationRecord
  belongs_to :user
  belongs_to :main_goal
  validates :dead_line, presence: true
  validates :sub_goal, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :main_goals, dependent: :destroy
  has_many :sub_goals, dependent: :destroy
  has_one :profile, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user])
  end
end

app/controllers/main_goals_controller.rb
class MainGoalsController < ApplicationController
  before_action :main_goal_set, only: [:edit, :update, :destroy]
  def index
    if user_signed_in?
      @main_goal = MainGoal.where(user_id: current_user.id)
      @sub_goal = SubGoal.where(main_goal: @main_goal.ids)
    end
  end
  def new
    @main_goal = MainGoal.new
  end
  def create
    @main_goal = MainGoal.new(main_goal_params)
    if @main_goal.save
      redirect_to root_path
    else
      render :new
    end
  end
  def show
    @main_goal = MainGoal.where(user_id: params[:id])
    @sub_goal = SubGoal.where(main_goal: @main_goal.ids)
    @profile = Profile.where(user_id: current_user.id).first
  end
  def edit
  end
  def update
    if @main_goal.update(main_goal_params)
      redirect_to main_goal_path(current_user.id)
    else
      render :edit
    end
  end
  def destroy
    @main_goal.destroy
    redirect_to main_goal_path(current_user.id)
  end
  private
  def main_goal_params
    params.require(:main_goal).permit(:main_goal, :explnation, :dead_line).merge(user_id: current_user.id)
  end 
  def main_goal_set
    @main_goal = MainGoal.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end
  def create
    @profile = Profile.new(params_profile)
    if @profile.save
      redirect_to  main_goal_path(current_user.id)
    else
      render :new
    end 
  end
  def edit
  end
  def update
  end
  private
  def params_profile
    params.require(:profile).permit(:name, :image, :life_goal, :life_goal_explanation, :profile).merge(user_id: current_user.id)
  end
end

app/controllers/sub_goals_controller.rb
class SubGoalsController < ApplicationController
  def new
    @sub_goal =SubGoal.new
  end
  def create
    @sub_goal =SubGoal.new(params_sub_goal)
    if @sub_goal.save
      redirect_to main_goal_path(current_user.id)
    else
      render :new
    end
  end
  def edit
    @main_goal = MainGoal.find(params[:main_goal_id])
    @sub_goal = SubGoal.find(params[:id])
  end
  def update
    @main_goal = MainGoal.find(params[:main_goal_id])
    @sub_goal = SubGoal.find(params[:id])
    @sub_goal.update(params_sub_goal)
    redirect_to main_goal_path(current_user.id)
  end
  def destroy
    @main_goal = MainGoal.find(params[:main_goal_id])
    @sub_goal = SubGoal.find(params[:id])
    @sub_goal.destroy
    redirect_to main_goal_path(current_user.id)
  end
  private
  def params_sub_goal
    params.require(:sub_goal).permit(:sub_goal, :dead_line).merge(user_id: current_user.id, main_goal_id: params[:main_goal_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_goals_helper.rb
module MainGoalsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sub_goals_helper.rb
module SubGoalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AchiveApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main_goals/edit.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class= new-main>
    <%=form_with model: @main_goal, local:true do |f|%>
      <p>目標</p>
      <div class="main-goal">
        <%= f.text_area :main_goal, placeholder:"目標を書こう！！", class:"input-form name"%>
      </div>
      <p>説明</p>
      <div class="main-goal">
        <%= f.text_area :explnation, placeholder:"目標について詳しく！！", class:"input-form explanation"%>
      </div>
      <p>締め切り</p>
      <p><span>(右のアイコンをクリック)</span></p>
      <div class="main-goal">
        <%= f.datetime_field :dead_line, class:"input-form dead-line"%>
      </div>
      <div class="main-goal">
      <%= f.submit "目標設定！！" ,class:"set-btn" %>
      </div>
    <%end%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/main_goals/index.html.erb
<%= render "shared/header" %>
<%= render partial: "shared/main", locals: { main_goal: @main_goal, sub_goal: @sub_goal } %>
<div class="others">
  <p>他の人の目標を見る</p>
</div>
<%= render "shared/footer" %>

app/views/main_goals/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class= new-main>
    <%=form_with model: @main_goal, local:true do |f|%>
      <p>目標</p>
      <div class="main-goal">
        <%= f.text_area :main_goal, placeholder:"目標を書こう！！", class:"input-form name"%>
      </div>
      <p>説明</p>
      <div class="main-goal">
        <%= f.text_area :explnation, placeholder:"目標について詳しく！！", class:"input-form explanation"%>
      </div>
      <p>締め切り</p>
      <p><span>(右のアイコンをクリック)</span></p>
      <div class="main-goal">
        <%= f.datetime_field :dead_line, class:"input-form dead-line"%>
      </div>
      <div class="main-goal">
      <%= f.submit "目標設定！！" ,class:"set-btn" %>
      </div>
    <%end%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/main_goals/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <% if user_signed_in?%>
    <% if @profile.present? %>
      <div class="profiles">
        <div class="profile">
          <div class="user-profiles">
            <div class="user-image">
            <%if @profile.image.attached?%>
            <%= image_tag @profile.image, class: 'image'%>
            <%else%>
            <%= image_tag "sample.png", class: 'image'%>
            <%end%>
            <h1 class="user-name"><%= @profile.name%></h1>
            </div>
            <div class="user-profile">
              <p class="profile-content">
              <%= @profile.profile%>
              </p>
            </div>
          </div>
          <div class="user-goal">
            <div class="life-goal">
              <h1 class="life-goal-content">
              <%= @profile.life_goal%>
              </h1>
            </div>
            <div class="life-goal-explanation">
              <p class="life-goal-explanation-content">
              <%= @profile.life_goal_explanation%>
              </p>
            </div>
          </div>
        </div>
        <div class="profile-edit">
          <%= link_to "プロフィールを編集する",new_profile_path %> 
        </div>
      </div>
    <% else %>
      <div class="profiles">
        <div class="profile">
          <div class="user-profiles">
            <div class="user-image">
            <%= image_tag "sample.png", class: 'image'%>
            <h1 class="user-name">プロフィール編集で入れよう！</h1>
            </div>
            <div class="user-profile">
              <p class="profile-content">
              自己紹介を書こう！！
              </p>
            </div>
          </div>
          <div class="user-goal">
            <div class="life-goal">
              <h1 class="life-goal-content">
              人生の目標を決めよう！！
              </h1>
            </div>
            <div class="life-goal-explanation">
              <p class="life-goal-explanation-content">
              </p>
            </div>
          </div>
        </div>
        <div class="profile-edit">
          <%= link_to "プロフィールを編集する",new_profile_path %> 
        </div>
      </div>
    <% end %>
      <% if @main_goal.present?%>
        <% @main_goal.each do |goal| %>
          <div class="goal">
            <div class="goal-content">
              <div class="main-goal-name">
              <h1><%= goal.main_goal %></h1>
              </div>
              <div class="main-goal-explnation ">
              <p><%= goal.explnation %></p>
              </div>
              <div class="sub-goals">
                <div class="sub-goals-contents">
                  <%@sub_goal.each do |sub_goal|%>
                    <div class="sub-goal">
                      <div class="sub-goal-edit">
                        <%=link_to "達成した！！",  main_goal_sub_goal_path(goal.id, sub_goal.id),method: :delete%>
                      </div>
                      <div class="sub-goal-name">
                        <%= sub_goal.sub_goal %>
                      </div>
                      <div class="sub-goal-limit">
                        <%= "残り
                        #{((sub_goal.dead_line-DateTime.now).to_i/(24*60*60)).floor}
                        日！！"%>
                      </div>
                    </div>
                  <% end %>
                  <%=link_to "サブ目標を追加する", new_main_goal_sub_goal_path(goal.id), id:"sub-goal-add-btn"%>
                </div>
              </div>
            </div>
            <div class="limit">
              <div class="goal-limit">
              <h2>残り</h2>
              <h1 id= "goal-limit" ><%= "#{goal.dead_line}" %> </h1>
              </div>
            </div>
          </div>
          <div class="goal-edit">
            <div class="edit">
              <%= link_to "編集する", edit_main_goal_path(goal.id) %>
            </div>
            <div class="destroy">
              <%= link_to "達成した！", main_goal_path(goal.id), method: :delete %>
            </div>
          </div>
        <% end %>
      <%else%>
        <h1 class="message">さぁ目標を決めよう！！</h1>
      <%end%>
        <div class="goal-set">
          <%=link_to "目標を追加する", new_main_goal_path %>
        </div>
    <%else%>
      <h1 class="message">ログインして仲間になろう！！</h1>
  <%end%>
</div>
<%= render "shared/footer" %>

app/views/profiles/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class= new-main>
    <%=form_with model: @profile, local:true do |f|%>
      <p>名前</p>
      <div class="main-goal">
        <%= f.text_area :name, class:"input-form name", maxlength:"40" %>
      </div>
      <p>プロフィール画像</p>
      <div class="main-goal">
        <%= f.file_field :image, id:"item-image" %>
      </div>
      <p>人生の目標</p>
      <div class="main-goal">
        <%= f.text_area :life_goal, placeholder:"目標を書こう！！", class:"input-form name"%>
      </div>
      <p>説明</p>
      <div class="main-goal">
        <%= f.text_area :life_goal_explanation, placeholder:"目標について詳しく！！", class:"input-form explanation"%>
      </div>
      <p>プロフィール</p>
      <div class="main-goal">
        <%= f.text_area :profile, class:"input-form explanation"%>
      </div>
      <div class="main-goal">
      <%= f.submit "プロフィール設定！！" ,class:"set-btn-profile" %>
      </div>
    <%end%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>提供</p>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="left-header">
    <%= link_to "Achive", root_path, class:"title-name" %>
  </div>
  <div class="center-header">
    <div class="search">
      <form class="search-form">
        <input type="text" placeholder="名前で検索" class="name-form">
        <input type="submit" value="検索" class="send">
      </form>
    </div>
  </div>
  <div class="right-header">
      <% if user_signed_in? %>
      <div class="right-header-left">
        <%= link_to 'マイページ', main_goal_path(current_user.id) %>
      </div>
      <div class="right-header-right">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      </div>
      <% else %>
      <div class="right-header-left">
        <%= link_to '新規登録',  new_user_registration_path %>
      </div>
      <div class="right-header-right">
        <%= link_to 'ログイン',  new_user_session_path %>
      </div>
      <% end %>
  </div>
</div>

app/views/shared/_main.html.erb
<div class="main">
  <% if user_signed_in?%>
    <% if main_goal.present?%>
      <% main_goal.each do |goal| %>
        <div class="goal">
          <div class="goal-content">
            <div class="main-goal-name">
              <h1><%= goal.main_goal %></h1>
            </div>
            <div class="main-goal-explnation ">
              <p><%= goal.explnation %></p>
            </div>
            <div class="sub-goals">
              <div class="sub-goals-contents">
                <%sub_goal.each do |sub_goal|%>
                  <div class="sub-goal">
                    <div class="sub-goal-name">
                      <%= sub_goal.sub_goal %>
                    </div>
                    <div class="sub-goal-limit">
                      <%= "残り#{((sub_goal.dead_line-DateTime.now).to_i/(24*60*60)).floor}日！！"%>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="limit">
            <div class="goal-limit">
            <h2>残り</h2>
            <h1 id= "goal-limit"><%= "#{goal.dead_line}" %> </h1>
            </div>
          </div>
        </div>
      <% end %>
    <%else%>
      <div class="goal-set-none">
        <h1 class="message">さぁ目標を決めよう！！</h1>
        <%=link_to "目標を設定する", new_main_goal_path %>
      </div>
    <%end%>
  <%else%>
    <div class="goal-set-none">
      <h1 class="message">ログインして仲間になろう！！</h1>
      </div>
  <%end%>
</div>

app/views/sub_goals/edit.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class= new-main>
    <%=form_with model: [@main_goal, @sub_goal] do |f|%>
      <p>目標</p>
      <div class="main-goal">
        <%= f.text_area :sub_goal, placeholder:"目標を書こう！！", class:"input-form name"%>
      </div>
      <p>締め切り</p>
      <p><span>(右のアイコンをクリック)</span></p>
      <div class="main-goal">
        <%= f.datetime_field :dead_line, class:"input-form dead-line"%>
      </div>
      <div class="sub-goal-set-btn">
        <%= f.submit "目標設定！！" ,class:"set-btn" %>
      </div>
    <%end%>
    <%=link_to "削除する",  main_goal_sub_goal_path(@main_goal, @sub_goal),id:"destroy-btn",method: :delete%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/sub_goals/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class= new-main>
    <%=form_with model: @sub_goal,url:  main_goal_sub_goals_path(params[:main_goal_id]), local:true do |f|%>
      <p>目標</p>
      <div class="main-goal">
        <%= f.text_area :sub_goal, placeholder:"目標を書こう！！", class:"input-form name"%>
      </div>
      <p>締め切り</p>
      <p><span>(右のアイコンをクリック)</span></p>
      <div class="main-goal">
        <%= f.datetime_field :dead_line, class:"input-form dead-line"%>
      </div>
      <div class="main-goal">
      <%= f.submit "目標設定！！" ,class:"set-btn" %>
      </div>
    <%end%>
  </div>
</div>
<%= render "shared/footer" %>